package com.ronny.gamemingle.ui.theme

import androidx.compose.ui.unit.dp

val EXTRA_LARGE_PADDING = 40.dp
val LARGE_PADDING = 20.dp
val MEDIUM_PADDING = 16.dp
val SMALL_PADDING = 10.dp
val EXTRA_SMALL_PADDING = 6.dp

val INDICATOR_SIZE = 10.dp
val PAGE_INDICATOR_WIDTH = 52.dp
val HERO_ITEM_HEIGHT = 400.dp

val NAME_PLACEHOLDER_HEIGHT = 30.dp
val ABOUT_PLACEHOLDER_HEIGHT = 20.dp
val RATING_PLACEHOLDER_HEIGHT = 20.dp
val RATING_PLACEHOLDER_WIDTH = 100.dp
val NETWORK_ERROR_ICON_SIZE = 120.dp

val SEARCH_TOP_BAR_HEIGHT = 56.dp
val ICON_SIZE = 32.dp
val INFO_ICON_SIZE = 25.dp
val MIN_SHEET_HEIGHT = 135.dp
val EXPANDED_RADIUS_LEVEL = 0.dp